from datetime import datetime

def generate_affidavit(action: dict, officer: dict) -> str:
    today = datetime.now().strftime("%d %B %Y")
    return f"""COMPLIANCE AFFIDAVIT

IN THE HIGH COURT OF KARNATAKA AT BENGALURU

Case: {action.get('judgment_case_number', 'W.P. ___/____')}

AFFIDAVIT OF COMPLIANCE

I, {officer.get('name', '_________________')}, {action.get('responsible_designation', '_________________')},
{action.get('responsible_department', 'Government of Karnataka')}, do hereby solemnly affirm and state as follows:

1. That the Hon'ble Court vide its order dated {action.get('order_date', '_______')} had directed as under:

   "{action.get('directive_text', '')}"

2. That I have complied with the above direction on {today}.

3. That the compliance has been carried out in letter and spirit and in accordance with the directions
   of this Hon'ble Court.

4. That the facts stated above are true and correct to the best of my knowledge and belief.

DEPONENT

Verified at Bengaluru on this {today}
The contents of this affidavit are true and correct to the best of my knowledge and belief.

_______________________
{officer.get('name', '')}
{action.get('responsible_designation', '')}
{action.get('responsible_department', '')}

[Generated by NyaaySetu — Court Compliance Management System]
"""
