'use client'
interface Props { text: string; onClose: () => void }

export default function AffidavitGenerator({ text, onClose }: Props) {
  const copyToClipboard = () => navigator.clipboard.writeText(text)
  const download = () => {
    const blob = new Blob([text], { type: 'text/plain' })
    const url = URL.createObjectURL(blob)
    const a = document.createElement('a')
    a.href = url; a.download = 'compliance_affidavit.txt'; a.click()
    URL.revokeObjectURL(url)
  }

  return (
    <div className="p-4">
      <div className="flex items-center justify-between mb-3">
        <h4 className="text-sm font-semibold text-slate-800">📄 Compliance Affidavit</h4>
        <button onClick={onClose} className="text-slate-400 hover:text-slate-600 text-lg">×</button>
      </div>
      <pre className="text-xs text-slate-700 bg-slate-50 border border-slate-200 rounded-lg p-3 whitespace-pre-wrap max-h-64 overflow-y-auto font-mono leading-relaxed">
        {text}
      </pre>
      <div className="flex gap-2 mt-3">
        <button onClick={copyToClipboard}
          className="flex-1 text-xs bg-slate-800 text-white py-2 rounded-lg hover:bg-slate-700 font-medium">
          📋 Copy to Clipboard
        </button>
        <button onClick={download}
          className="flex-1 text-xs bg-green-600 text-white py-2 rounded-lg hover:bg-green-700 font-medium">
          ⬇️ Download .txt
        </button>
      </div>
      <p className="text-xs text-slate-400 mt-2 text-center">Generated by NyaaySetu · For filing in court</p>
    </div>
  )
}
